-- 1. Mostrar a los alumnos que no son invictos.

SELECT NOMBRE NO_INVICTOS FROM ALUMNO
WHERE ALUMNO IN (
	SELECT ALUMNO FROM ALUMNOCURSO WHERE PROMEDIO <= 10
	)
ORDER BY NOMBRE

-- 2. Mostrar a los alumnos con sus promedios ponderados.

SELECT A.NOMBRE, TO_CHAR(SUM(AC.PROMEDIO * C.CREDITOS)/SUM(C.CREDITOS),'FM99999.00') PROMEDIO_PONDERADO FROM ALUMNOCURSO AC
INNER JOIN CURSO C ON AC.CURSO = C.CURSO
INNER JOIN ALUMNO A ON AC.ALUMNO = A.ALUMNO
GROUP BY A.NOMBRE
ORDER BY SUM(AC.PROMEDIO * C.CREDITOS)/SUM(C.CREDITOS) DESC

-- 3. Mostrar el mayor promedio ponderado.

SELECT MAX(SUM(AC.PROMEDIO * C.CREDITOS)/SUM(C.CREDITOS)) MAYOR_PROMEDIO_PONDERADO FROM ALUMNOCURSO AC
INNER JOIN CURSO C ON AC.CURSO = C.CURSO
INNER JOIN ALUMNO A ON AC.ALUMNO = A.ALUMNO
GROUP BY A.ALUMNO

-- 4. Mostrar a los alumnos invictos.

SELECT NOMBRE INVICTOS FROM ALUMNO
WHERE ALUMNO NOT IN (
	SELECT ALUMNO FROM ALUMNOCURSO WHERE PROMEDIO <= 10
	)
ORDER BY NOMBRE

-- 5. Mostrar los alumnos que han aprobado al menos un curso.

SELECT A.NOMBRE TIENE_APROBADO FROM ALUMNOCURSO AC
INNER JOIN ALUMNO A ON AC.ALUMNO = A.ALUMNO
WHERE AC.PROMEDIO > 10
GROUP BY A.NOMBRE
ORDER BY A.NOMBRE

-- 6. Determinar los alumnos que están en el tercio superior.

SELECT T.NOMBRE TERCIO_SUPERIOR, T.PROMEDIO_PONDERADO FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY SUM(AC.PROMEDIO * C.CREDITOS)/SUM(C.CREDITOS) DESC) PUESTO, A.NOMBRE, TO_CHAR(SUM(AC.PROMEDIO * C.CREDITOS)/SUM(C.CREDITOS),'FM99999.00') PROMEDIO_PONDERADO FROM ALUMNO A
    LEFT JOIN ALUMNOCURSO AC ON AC.ALUMNO = A.ALUMNO
    LEFT JOIN CURSO C ON AC.CURSO = C.CURSO
    WHERE AC.CURSO IS NOT NULL
    GROUP BY A.NOMBRE
    ) T
WHERE T.PUESTO <= (SELECT COUNT(1)/3 FROM ALUMNO)

-- 7. Mostrar los alumnos que hayan aprobado todos los cursos, tengan como promedio general mínimo 13 (media aritmética de promedios de todos sus cursos) y que tengan al menos 2 promedios de curso mayores o iguales a 15.

SELECT A.NOMBRE ALUMNO, TO_CHAR(SUM(AC.PROMEDIO)/COUNT(1),'FM99999.00') PROMEDIO_ARITMETICO FROM ALUMNO A
    LEFT JOIN ALUMNOCURSO AC ON AC.ALUMNO = A.ALUMNO
    LEFT JOIN CURSO C ON AC.CURSO = C.CURSO
    WHERE A.ALUMNO NOT IN (
	    SELECT ALUMNO FROM ALUMNOCURSO WHERE PROMEDIO <= 10
	    ) AND A.ALUMNO IN (
	    SELECT T.ALUMNO FROM (
            SELECT A.ALUMNO,SUM(AC.PROMEDIO)/COUNT(1) PROMEDIO_ARITMETICO FROM ALUMNO A
            LEFT JOIN ALUMNOCURSO AC ON AC.ALUMNO = A.ALUMNO
            LEFT JOIN CURSO C ON AC.CURSO = C.CURSO
            GROUP BY A.ALUMNO,C.NOMBRE
            HAVING SUM(AC.PROMEDIO)/COUNT(1) >= 15
            ) T
        HAVING COUNT(1) >=  2
    GROUP BY T.ALUMNO)
GROUP BY A.NOMBRE
HAVING SUM(AC.PROMEDIO)/COUNT(1) >= 13