-- 1. Mostrar los alumnos que han rendido el examen 1.

SELECT A.NOMBRE RINDIERON_EXAMEN_1 FROM NOTA N
INNER JOIN ALUMNO A ON N.ALUMNO = A.ALUMNO
WHERE TIPO = 1 -- EXAMEN
AND NUMEVAL = 1 -- NUMERO EXAMEN
GROUP BY A.NOMBRE
ORDER BY A.NOMBRE

-- 2. Mostrar los alumnos que han rendido el examen 2.

SELECT A.NOMBRE RINDIERON_EXAMEN_2 FROM NOTA N
INNER JOIN ALUMNO A ON N.ALUMNO = A.ALUMNO
WHERE TIPO = 1 -- EXAMEN
AND NUMEVAL = 2 -- NUMERO EXAMEN
GROUP BY A.NOMBRE
ORDER BY A.NOMBRE

-- 3. Mostrar los alumnos del curso ADM301 que han rendido la práctica 1.

SELECT A.NOMBRE ADM301_PRACTICA_1 FROM NOTA N
INNER JOIN ALUMNO A ON N.ALUMNO = A.ALUMNO
WHERE N.CURSO = 'ADM301'
AND TIPO = 2 -- PRACTICA
AND NUMEVAL = 1 -- NUMERO PRACTICA
GROUP BY A.NOMBRE
ORDER BY A.NOMBRE

-- 4. Mostrar los alumnos del curso ADM322 que han rendido la práctica 2.

SELECT A.NOMBRE ADM322_PRACTICA_2 FROM NOTA N
INNER JOIN ALUMNO A ON N.ALUMNO = A.ALUMNO
WHERE N.CURSO = 'ADM322'
AND TIPO = 2 -- PRACTICA
AND NUMEVAL = 2 -- NUMERO PRACTICA
GROUP BY A.NOMBRE
ORDER BY A.NOMBRE

-- 5. Mostrar los alumnos que han aprobado el examen 1.

SELECT A.NOMBRE APROBADOS_EXAMEN_1 FROM NOTA N
INNER JOIN ALUMNO A ON N.ALUMNO = A.ALUMNO
WHERE TIPO = 1 -- EXAMEN
AND NUMEVAL = 1 -- NUMERO EXAMEN
AND NOTA > 10
GROUP BY A.NOMBRE
ORDER BY A.NOMBRE

-- 6. Mostrar los alumnos que tienen alguna nota desaprobada.

SELECT A.NOMBRE CON_DESAPROBADO FROM NOTA N
INNER JOIN ALUMNO A ON N.ALUMNO = A.ALUMNO
WHERE NOTA <= 10
GROUP BY A.NOMBRE
ORDER BY A.NOMBRE

-- 7. Mostrar los alumnos que tienen alguna nota aprobada.

SELECT A.NOMBRE CON_APROBADO FROM NOTA N
INNER JOIN ALUMNO A ON N.ALUMNO = A.ALUMNO
WHERE NOTA > 10
GROUP BY A.NOMBRE
ORDER BY A.NOMBRE

-- 8. Mostrar los cursos que tienen algún examen aprobado.

SELECT A.NOMBRE CON_EXAMEN_APROBADO FROM NOTA N
INNER JOIN ALUMNO A ON N.ALUMNO = A.ALUMNO
WHERE NOTA > 10
AND TIPO = 1 -- EXAMEN
GROUP BY A.NOMBRE
ORDER BY A.NOMBRE

-- 9. Mostrar los cursos que tienen alguna práctica aprobada.

SELECT A.NOMBRE CON_PRACTICA_DESAPROBADA FROM NOTA N
INNER JOIN ALUMNO A ON N.ALUMNO = A.ALUMNO
WHERE NOTA <= 10
AND TIPO = 2 -- PRACTICA
GROUP BY A.NOMBRE
ORDER BY A.NOMBRE